# Generated by Django 4.1.7 on 2024-06-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruleName', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
            ],
        ),
    ]
