# Generated by Django 4.1.7 on 2024-06-24 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rulem', '0002_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rulem.rules')),
            ],
        ),
    ]
