# Generated by Django 4.1.7 on 2024-07-07 17:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rulem', '0005_alter_rules_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='id_upload',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
